---
title: "GA_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Load packages
library(raster)
library(tidyverse)
library(sf)
library(here)
library(fasterize)
library(stringr)
library(janitor)
library(prioritizr)
library(rgdal)
library(slam)
library(tmap)
library(s2)
library(gurobi)

```

1. Planning unit: 
Set up the GA area as a raster and a simple features file
```{r}

########################
#read in the project area raster
GA_rast <- raster(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/2_Grid/grid_rast_84/grid_rast_84.tif"))

plot(GA_rast)
crs(GA_rast)
# proj4string(GA_rast) <- CRS("+proj=utm +zone=10+datum=WGS84")
# proj4string(GA_rast) 
# crs(GA_rast) <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
# crs(GA_rast)
# plot(GA_rast)


#######################
## Set up GA Area as a simple feature file and the extent file
GA_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/2_Grid/Grid_2.shp"))

## Check coordinate system
st_crs(GA_sf)
extent(GA_sf)

## change the CRS to WGS 1984, and extent to lat/long instead of decimals
GA_sf <- st_transform(GA_sf, crs = 4326)
st_crs(GA_sf)
extent(GA_sf)

## Use Moz EEZ to set extent for future rasters
GA_ext <- raster::extent(GA_sf)

```

2. Conservation Features

Protected Areas, MPAs
```{r}

#read in protected areas and existing MPAs

pa_path <- 'C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/WDPA_WDOECM_SA_Polyg_ALL_GAE'
pa_shape <- list.files(pa_path, full.names = TRUE)

## Load shapefile as simple feature
pa_sf <- sf::read_sf(pa_shape[8]) 

## Check the CRS of the pa's and compare to the GA rast
st_crs(GA_rast)
st_crs(pa_sf)

## Let's create a raster using the mz_rast and mask to the GA area
pa <- fasterize::fasterize(pa_sf, GA_rast) %>%
  mask(GA_sf)

## Plot to see what it looks like
plot(pa)

# Looks good lets save as a tif
writeRaster(pa, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_pa.tif'), overwrite = TRUE)



```

Species data - TURTLES Occurrence and Nesting Data
```{r}

#Turtle Occurance data
#ALL turtles: Olive, Green, Loggerhead, Hawksbill, Leatherback#

turtle_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/turtles/Nesting Data Widecast/green_proj.shp"))
turtle_sf <- st_transform(turtle_sf, crs = 4326)
st_crs(turtle_sf)
turtle_sf
plot(turtle_sf)

turtle_rast = rasterize(turtle_sf, GA_rast, "diss", fun = max) %>% 
  mask(GA_sf)

plot(turtle_rast)

writeRaster(turtle_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_turtle_all.tif'), overwrite = TRUE)

#################
#Turtle Nesting Data
#May 4, 2021

nest_may_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/turtles/Nesting Data Widecast/nest_may4_proj.shp"))
nest_may_sf <- st_transform(nest_may_sf, crs = 4326)
st_crs(nest_may_sf)
nest_may_sf
plot(nest_may_sf)

nest_may_rast = rasterize(nest_may_sf, GA_rast, "diss", fun = max)

plot(nest_may_rast)

writeRaster(nest_may_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_nest_may.tif'), overwrite = TRUE)

#April 24, 2021

nest_april_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/turtles/Nesting Data Widecast/nest_april24_proj.shp"))
nest_april_sf <- st_transform(nest_april_sf, crs = 4326)
st_crs(nest_april_sf)
nest_april_sf
plot(nest_april_sf)

nest_april_rast = rasterize(nest_april_sf, GA_rast, "diss", fun = max)

plot(nest_april_rast)

writeRaster(nest_april_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_nest_april.tif'), overwrite = TRUE)

#March 21, 2021

nest_march_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/turtles/Nesting Data Widecast/nest_mar21_proj.shp"))
nest_march_sf <- st_transform(nest_march_sf, crs = 4326)
st_crs(nest_march_sf)
nest_march_sf
plot(nest_march_sf)

nest_march_rast = rasterize(nest_march_sf, GA_rast, "diss", fun = max)

plot(nest_march_rast)

writeRaster(nest_march_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_nest_march.tif'), overwrite = TRUE)


# #Green#
# green_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/turtles/Nesting Data Widecast/green_proj.shp"))
# green_sf <- st_transform(green_sf, crs = 4326)
# st_crs(green_sf)
# green_sf
# plot(green_sf)
# 
# green_rast = rasterize(green_sf, GA_rast, "diss", fun = max) %>% 
#   mask(GA_sf)
# 
# plot(green_rast)
# 
# writeRaster(green_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_green.tif'), overwrite = TRUE)
# 
# ########
# #loggerheads#
# logger_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/turtles/Nesting Data Widecast/logger_proj.shp")) %>% 
#   select(-c(Green, Hawksbill:Olive_Ridl))
# logger_sf <- st_transform(logger_sf, crs = 4326)
# st_crs(logger_sf)
# logger_sf
# plot(logger_sf)
# 
# logger_rast = rasterize(logger_sf, GA_rast, "diss", fun = max) %>% 
#   mask(GA_sf)
# 
# plot(logger_rast)
# 
# writeRaster(logger_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_logger.tif'), overwrite = TRUE)



```


Habitat data
```{r}

#mangroves
mangrove_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Mangrove_watch/mangroves.shp"))
mangrove_sf <- st_transform(mangrove_sf, crs = 4326)
st_crs(mangrove_sf)
mangrove_sf
plot(mangrove_sf)

mangrove_rast = rasterize(mangrove_sf, GA_rast, "pxlval", fun = max)

plot(mangrove_rast)

writeRaster(mangrove_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_mangrove.tif'), overwrite = TRUE)

#seagrasses
seagrasses_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/WCMC013014_Seagrasses_Py_v7_GAE/WCMC013014_Seagrasses_Py_v7_GAE.shp")) %>% 
  mutate(diss = 1)
seagrasses_sf <- st_transform(seagrasses_sf, crs = 4326)
st_crs(seagrasses_sf)
seagrasses_sf
plot(seagrasses_sf)

seagrasses_rast = rasterize(seagrasses_sf, GA_rast, "diss", fun = max)

plot(seagrasses_rast)

writeRaster(seagrasses_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_seagrasses.tif'), overwrite = TRUE)

#salt marshes
saltmarsh_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/WCMC027_Saltmarshes_Py_v6_GAE/WCMC027_Saltmarshes_Py_v6_GAE.shp")) %>% 
  mutate(diss = 1)
saltmarsh_sf <- st_transform(saltmarsh_sf, crs = 4326)
st_crs(saltmarsh_sf)
saltmarsh_sf
plot(saltmarsh_sf)

saltmarsh_rast = rasterize(saltmarsh_sf, GA_rast, "diss", fun = max)

plot(saltmarsh_rast)

writeRaster(saltmarsh_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_saltmarsh.tif'), overwrite = TRUE)

#cold corals
coldcoral_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Cold_Corals_2017_Pt_v5_Buffer500m_GAE/Cold_Corals_2017_Pt_v5_Buffer500m_GAE.shp")) %>% 
  mutate(diss = 1)
coldcoral_sf <- st_transform(coldcoral_sf, crs = 4326)
st_crs(coldcoral_sf)
coldcoral_sf
plot(coldcoral_sf)

coldcoral_rast = rasterize(coldcoral_sf, GA_rast, "diss", fun = max)

plot(coldcoral_rast)

writeRaster(coldcoral_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_coldcoral.tif'), overwrite = TRUE)

#coral reefs TNC
coral_TNC_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/WCMC008_CoralReef2018_Py_v4_GAE/WCMC008_CoralReef2018_Py_v4_GAE.shp")) %>% 
  mutate(diss = 1)
coral_TNC_sf <- st_transform(coral_TNC_sf, crs = 4326)
st_crs(coral_TNC_sf)
coral_TNC_sf
plot(coral_TNC_sf)

coral_TNC_rast = rasterize(coral_TNC_sf, GA_rast, "diss", fun = max)

plot(coral_TNC_rast)

writeRaster(coral_TNC_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_coral_TNC.tif'), overwrite = TRUE)

#TNC mangroves and saltmarshes
mansalt_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Mangroves_Saltmarshes_HerbazalesCienaga_Saladares_GAE_Ensemble/Mangroves_Saltmarshes_HerbazalesCienaga_Saladares_GAE_Ensemble.shp")) %>% 
  mutate(diss = 1)
mansalt_sf <- st_transform(mansalt_sf, crs = 4326)
st_crs(mansalt_sf)
mansalt_sf
plot(mansalt_sf)


mansalt_rast = rasterize(mansalt_sf, GA_rast, "diss", fun = max)

plot(mansalt_rast)

writeRaster(mansalt_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_mansalt.tif'), overwrite = TRUE)

#mangroves - World Atlas of Mangroves
man_WAM_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/WCMC011_AtlasMangrove2010_Py_v3_GAE/WCMC011_AtlasMangrove2010_Py_v3_GAE.shp")) %>% 
  mutate(diss = 1)
man_WAM_sf <- st_transform(man_WAM_sf, crs = 4326)
st_crs(man_WAM_sf)
man_WAM_sf
plot(man_WAM_sf)

man_WAM_rast = rasterize(man_WAM_sf, GA_rast, "diss", fun = max)

plot(man_WAM_rast)

writeRaster(man_WAM_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_man_WAM.tif'), overwrite = TRUE)

```


3. Geomorfological and geological features
```{r}

#Abyssal plain
abyssal_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Abyssal_Plain_3300_4800_GAE/Abyssal_Plain_3300_4800_GAE.shp")) %>% 
  mutate(diss = 1)
abyssal_sf <- st_transform(abyssal_sf, crs = 4326)
st_crs(abyssal_sf)
abyssal_sf
plot(abyssal_sf)

abyssal_rast = rasterize(abyssal_sf, GA_rast, "diss", fun = max)

plot(abyssal_rast)

writeRaster(abyssal_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_abyssal.tif'), overwrite = TRUE)

#Various coastal benthic TNC
benthic_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/GAE_TNC_mar_benhab4m_2021_Diss7_GRASS_Diss/GAE_TNC_mar_benhab4m_2021_Diss7_GRASS_Diss_HG.shp")) %>% 
  mutate(diss = 1)
benthic_sf <- st_transform(benthic_sf, crs = 4326)
st_crs(benthic_sf)
benthic_sf
plot(benthic_sf)

benthic_rast = rasterize(benthic_sf, GA_rast, "diss", fun = max)

plot(benthic_rast)

writeRaster(benthic_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_benthic.tif'), overwrite = TRUE)

#Insular shelf

insular_shelf_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Insular_Shelf_GAE/Insular_Shelf_GAE.shp")) %>% 
  mutate(diss = 1)
insular_shelf_sf <- st_transform(insular_shelf_sf, crs = 4326)
st_crs(insular_shelf_sf)
insular_shelf_sf
plot(insular_shelf_sf)

insular_rast = rasterize(insular_shelf_sf, GA_rast, "diss", fun = max)

plot(insular_rast)

writeRaster(insular_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_insular_shelf.tif'), overwrite = TRUE)

#Insular upper shelf
insular_upper_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Insular_Upper_Shelf_Slope_Mesophotic_GAE/Insular_Upper_Shelf_Slope_Mesophotic_GAE.shp")) %>% 
  mutate(diss = 1)
insular_upper_sf <- st_transform(insular_upper_sf, crs = 4326)
st_crs(insular_upper_sf)
insular_upper_sf
plot(insular_upper_sf)

insular_upper_rast = rasterize(insular_upper_sf, GA_rast, "diss", fun = max)

plot(insular_upper_rast)

writeRaster(insular_upper_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_insular_upper.tif'), overwrite = TRUE)

#Isobata 
isobata_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Isobata0_TierraFirme_GAE/Isobata0_TierraFirme_GAE.shp")) %>% 
  mutate(diss = 1)
isobata_sf <- st_transform(isobata_sf, crs = 4326)
st_crs(isobata_sf)
isobata_sf
plot(isobata_sf)

isobata_rast = rasterize(isobata_sf, GA_rast, "diss", fun = max)

plot(isobata_rast)

writeRaster(isobata_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_isobata.tif'), overwrite = TRUE)


###################
####################
#####################
#####NEED TO LOOK AT REMOVING Z DIMENSIONA TO RASTERIZE#####
#Isobata GEBCO

isobata_GEBCO_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Gebco_2020_Caribe2_5m_isobata200_Clip_TM_World_Bordes_03_4/Gebco_2020_Caribe2_5m_isobata200_Clip_TM_World_Bordes_03_4.shp")) %>% 
  mutate(diss = 1)
isobata_GEBCO_sf <- st_transform(isobata_GEBCO_sf, crs = 4326)
st_crs(isobata_GEBCO_sf)
st_zm(isobata_GEBCO_sf)
isobata_GEBCO_sf
plot(isobata_GEBCO_sf)

isobata_GEBCO_rast = rasterize(isobata_GEBCO_sf, GA_rast, "diss", fun = max)

plot(isobata_GEBCO_rast)

writeRaster(isobata_GEBCO_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_isobata_GEBCO.tif'), overwrite = TRUE)


#Geomorphology Features 
geomorph_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Geology_Geomorphology_BiggestFeatures_GAE/Geology_Geomorphology_BiggestFeatures_GAE.shp")) %>%
  mutate(diss = 1)
geomorph_sf <- st_transform(geomorph_sf, crs = 4326)
st_crs(geomorph_sf)
geomorph_sf
plot(geomorph_sf)

geomorph_rast = rasterize(geomorph_sf, GA_rast, "diss", fun = max)

plot(geomorph_rast)

writeRaster(geomorph_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_geomorph_features.tif'), overwrite = TRUE)

#plateaus 
plateaus_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Plateaus_GAE/Plateaus_GAE.shp")) %>%
  mutate(diss = 1)
plateaus_sf <- st_transform(plateaus_sf, crs = 4326)
st_crs(plateaus_sf)
plateaus_sf
plot(plateaus_sf)

plateaus_rast = rasterize(plateaus_sf, GA_rast, "diss", fun = max)

plot(plateaus_rast)

writeRaster(plateaus_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_plateaus.tif'), overwrite = TRUE)

#ridges
ridges_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/Ridges_GAE_2/Ridges_GAE_2.shp")) %>%
  mutate(diss = 1)
ridges_sf <- st_transform(ridges_sf, crs = 4326)
st_crs(ridges_sf)
ridges_sf
plot(ridges_sf)

ridges_rast = rasterize(ridges_sf, GA_rast, "diss", fun = max)

plot(ridges_rast)

writeRaster(ridges_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_ridges.tif'), overwrite = TRUE)

#spreading ridges
spreading_ridges_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/RiftValleys_SpreadingRidges_GAE/RiftValleys_SpreadingRidges_GAE.shp")) %>%
  mutate(diss = 1)
spreading_ridges_sf <- st_transform(spreading_ridges_sf, crs = 4326)
st_crs(spreading_ridges_sf)
spreading_ridges_sf
plot(spreading_ridges_sf)

spreading_ridges_rast = rasterize(spreading_ridges_sf, GA_rast, "diss", fun = max)

plot(spreading_ridges_rast)

writeRaster(spreading_ridges_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_spreading_ridges.tif'), overwrite = TRUE)

#KGA features
KGA_features_sf <- sf::read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/1_sources/Rey/KGA_Features_GAE/KGA_Features_GAE.shp")) %>%
  mutate(diss = 1)
KGA_features_sf <- st_transform(KGA_features_sf, crs = 4326)
st_crs(KGA_features_sf)
KGA_features_sf
plot(KGA_features_sf)

KGA_features_rast = rasterize(KGA_features_sf, GA_rast, "diss", fun = max)

plot(KGA_features_rast)

writeRaster(KGA_features_rast, here('C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/VR files/VR Files/outputs/GA_KGA_features.tif'), overwrite = TRUE)


```



PARKING LOT
ALT TBD Set up the GA area as a raster
```{r}

#################
#HOLD ON DOING THESE NEXT STEPS
#################

## Create raster with cell ids and clip to MZ EEZ raster
GA_rast <- raster::raster(x=GA_ext, crs=crs(GA_sf), res = )

## Assign cell values
values(GA_rast) <- 1:ncell(GA_rast) 

## Create data frame to check it out
GA_rast_df <- rasterToPoints(GA_rast) %>%
  as.data.frame()

## Plot to make sure it looks good
plot(GA_rast)

## Mask it to only include the EEZ
GA_rast <- mask(GA_rast, GA_sf)
plot(GA_rast)

## Let's save this cell id raster as tif file - hashtagged this out for now since the tif is too big
writeRaster(GA_rast, here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/2_Grid/GA_rast.tif"), overwrite = TRUE)

```

Different approach to GA raster 
```{r}

#project area and planning units (grid of X km2)??

GA_grid <- read_sf(here("C:/Users/vanessa_rathbone/Dropbox/Greater_Antilles/2_Grid/Grid_2.shp")) %>% 
  st_set_crs(4326)

st_crs(GA_grid)

GA_grid <- sf::sf_use_s2(FALSE)

  s2::s2_rebuild() %>% 
  sf::st_as_sfc()

####### NEED TO FIX using yer_object$geometry <- yer_object$geometry %>% s2::s2_rebuild() %>% sf::st_as_sfc() OR sf::sf_use_s2(FALSE)
  
## Add a buffer of 10 km to make sure cells on the outer edges of the EEZ are included
GA_grid_buffer_sf <- sf::st_buffer(GA_grid, dist = 10000)


## Create data frame from simple feature to see data more readily (not necessary, but helpful for larger sf)
GA_grid_df <- GA_grid %>% as.data.frame() %>% select(-geometry)

## Use GA_grid to set extent for future rasters
GA_ext <- raster::extent(GA_grid)


```
